// AMOC Fragentyp 3 – Neue Folienlücken, Teil C

// Ligandenfeld / MO von Komplexen
t4("Teil 1","Ligandenfeld","Wie behandelt die einfache Kristallfeldtheorie die Liganden zunächst?","Als Punktladungen bzw. elektrostatische Donorzentren, die mit den Metall-d-Elektronen wechselwirken.","Als vollständig kovalente Molekülorbitale ohne elektrostatischen Anteil.","Als neutrale Teilchen ohne Elektronen.","Als Metallcluster.","Die Theorie startet mit einem elektrostatischen Modell.");
t4("Teil 1","Ligandenfeld","Welche zwei Beiträge unterscheidet die Folie bei der Wirkung des Ligandenfelds auf die d-Orbitale?","Eine gemeinsame kugelsymmetrische Destabilisierung aller d-Orbitale und zusätzlich eine symmetrieabhängige Aufspaltung.","Nur eine symmetrieabhängige Aufspaltung ohne gemeinsame Energieänderung.","Nur eine Absenkung aller d-Orbitale.","Ausschließlich Spin-Bahn-Kopplung.","Erst Kugelfeld, dann Aufhebung der Entartung.");
t4("Teil 1","Ligandenfeld","Was besagt der Schwerpunktsatz bei der Ligandenfeldaufspaltung?","Die Aufspaltung verteilt die Energien um den Schwerpunkt; insgesamt wird durch die Aufspaltung allein keine Energie gewonnen oder verloren.","Alle d-Orbitale werden durch die Aufspaltung gleich stark stabilisiert.","Der Schwerpunkt verschiebt sich immer um Δo nach unten.","Nur eg trägt zum Schwerpunkt bei.","Die gewichtete mittlere Energie bleibt gleich.");
t4("Teil 1","Ligandenfeld","Welche Ionen verursachen die charakteristische Farbe von Rubin bzw. Saphir in Korund laut Folie?","Rubin: Cr3+; Saphir: Ti3+.","Rubin: Ti3+; Saphir: Cr3+.","Rubin: Fe2+; Saphir: Co2+.","Beide Farben entstehen ausschließlich durch O2−.","Fremdionen sitzen in Oktaederlücken.");
t4("Teil 1","Ligandenfeld","Wie verändert eine höhere positive Ladung des Zentralmetalls im Allgemeinen Δ?","Δ nimmt zu.","Δ nimmt ab.","Δ bleibt unverändert.","Δ wird exakt null.","Höhere Ladung verstärkt M–L-Wechselwirkung.");
t4("Teil 1","Ligandenfeld","Welche Reihenfolge der Ligandenfeldaufspaltung gilt für gleiche Liganden beim Übergang 3d → 4d → 5d?","Δ nimmt von 3d über 4d zu 5d zu.","Δ nimmt kontinuierlich ab.","3d und 5d sind gleich, 4d ist null.","Es gibt keinen Trend.","Radial ausgedehntere d-Orbitale überlappen stärker.");
t4("Teil 1","Ligandenfeld","Welche Reihenfolge steht in der spektrochemischen Reihe korrekt bezüglich SCN− und NCS−?","SCN− liegt deutlich schwächer als NCS−.","NCS− liegt deutlich schwächer als SCN−.","Beide sind immer exakt gleich starke Liganden.","SCN− und NCS− stehen beide rechts von CO.","Bindungsatom des ambidenten Liganden beeinflusst Δ.");
t4("Teil 1","Ligandenfeld","Wie groß ist die tetraedrische Aufspaltung Δt relativ zu Δo laut Folie?","Δt = 4/9 Δo.","Δt = 9/4 Δo.","Δt = Δo.","Δt = 1/9 Δo.","Das tetraedrische Feld ist deutlich schwächer.");
t4("Teil 1","Ligandenfeld","Welche high-spin-d-Konfigurationen besitzen im Oktaederfeld laut LFSE-Tabelle keine Ligandenfeldstabilisierung?","d0, d5 und d10.","d1, d4 und d9.","d2, d6 und d8.","Nur d10.","Bei diesen Konfigurationen hebt sich Stabilisierung und Destabilisierung auf.");
t4("Teil 1","Ligandenfeld","Bei welchen high-spin-d-Konfigurationen zeigt die Oktaederpräferenz in der LFSE-Tabelle besonders ausgeprägte Maxima?","d3 und d8.","d0 und d10.","d5 ausschließlich.","d1 und d9.","Die Tabelle zeigt denselben starken Wert zweimal.");
t4("Teil 1","Ligandenfeld","Warum kann V2+ im oktaedrischen Feld einen relativ kleinen Ionenradius zeigen?","Bei d3 sind die eg-Orbitale in Ligandenrichtung unbesetzt, sodass Liganden näher herankommen können.","Bei d3 sind alle eg-Orbitale doppelt besetzt und ziehen Liganden an.","V2+ besitzt keine d-Elektronen.","V2+ ist immer tetraedrisch.","eg-Besetzung wirkt direkt entlang der M–L-Achsen.");
t4("Teil 1","Ligandenfeld","Welche strukturelle Änderung wird beim Übergang von high-spin zu low-spin Fe2+ im Porphyrin hervorgehoben?","Low-spin Fe2+ kontrahiert in die Porphyrin-Ringebene.","Low-spin Fe2+ wird deutlich größer und tritt aus der Ringebene heraus.","High-spin und low-spin haben exakt denselben Radius.","Low-spin Fe2+ verliert alle Liganden.","Die Folie verknüpft dies mit oxy/desoxy.");
t4("Teil 1","Ligandenfeld","Welche low-spin-d8-Metallionen nennt die Folie als typische quadratisch-planare Fälle?","Ir(I), Rh(I), Pd(II), Pt(II) und Au(III).","Cr(III), Mn(II), Fe(III), Co(II).","Ti(IV), V(V), Cr(VI).","Ag(I), Au(I) und Zn(II) ausschließlich.","Quadratisch-planar ist klassisch für low-spin d8.");
t4("Teil 1","Komplex-MO","Welche Symmetrie besitzt das Metall-s-Orbital im oktaedrischen MO-Schema?","a1g.","t1u.","eg.","t2g.","Das totalsymmetrische Orbital.");
t4("Teil 1","Komplex-MO","Welche Symmetrie besitzen die Metall-p-Orbitale px, py, pz im oktaedrischen MO-Schema?","t1u.","a1g.","eg.","t2g.","Drei p-Orbitale bilden einen dreifach entarteten Satz.");
t4("Teil 1","Komplex-MO","Welche Symmetrie besitzen dx2−y2 und dz2 im oktaedrischen Komplex?","eg.","t2g.","t1u.","a1g.","Die beiden auf die Ligandenachsen gerichteten d-Orbitale.");
t4("Teil 1","Komplex-MO","Welche Symmetrie besitzen dxy, dxz und dyz im oktaedrischen Komplex?","t2g.","eg.","t1u.","a2u.","Die drei zwischen den Achsen liegenden d-Orbitale.");
t4("Teil 1","Komplex-MO","Welche elektronischen Voraussetzungen besitzt ein π-Donor-Ligand?","Ein besetztes p- bzw. π-Orbital, das in ein geeignetes Metallorbital donieren kann.","Nur leere π*-Orbitale.","Keine freien Elektronenpaare und keine besetzten p-Orbitale.","Ausschließlich ein σ*-Orbital.","Donation verlangt besetzte Ligandenorbitale.");
t4("Teil 1","Komplex-MO","Welche elektronischen Voraussetzungen besitzt ein π-Akzeptor-Ligand?","Leere p-Orbitale oder niedrigliegende π*-Orbitale.","Nur vollständig besetzte p-Orbitale ohne Akzeptorfunktion.","Keine σ-Donorfähigkeit.","Nur sehr hoch liegende antibindende Orbitale.","Rückbindung erfolgt in ein leeres Ligandenorbital.");
t4("Teil 1","Komplex-MO","Welche Rollen besitzen HOMO und LUMO von CO im Metall-CO-Bindungsmodell?","Das HOMO dient als σ-Donororbital, die zweifach entarteten LUMO-π*-Orbitale als Akzeptoren für Rückbindung.","Das HOMO ist ausschließlich π-Akzeptor und das LUMO σ-Donor.","Beide sind nur nichtbindend und beteiligen sich nicht.","CO besitzt kein geeignetes LUMO.","Synergistische σ-Donation und π-Rückbindung.");
t4("Teil 1","18-Elektronenregel","Welcher der folgenden Komplexe wird in der Folie ausdrücklich als 16-Elektronen-Beispiel gezeigt?","[PtCl2(NH3)2].","[Co(NH3)6]3+.","Fe(CN)6^2−.","M(CO)6 mit M = Cr, Mo, W.","Die Folie zeigt bewusste Abweichungen von 18e.");
t4("Teil 1","18-Elektronenregel","Welcher weitere klassische 16-Elektronen-Komplex steht auf der Ausnahmeliste?","[Ir(CO)(Cl)(PPh3)2].","[MnO4]−.","[TiF6]2−.","[Co(NH3)6]3+.","Wilkinson-artige d8-Systeme können mit 16e stabil sein.");
t4("Teil 1","18-Elektronenregel","Warum ist die 18-Elektronenregel bei hochoxidierten Komplexen mit σ/π-Donor-Liganden oft ungeeignet?","Die Bindungssituation und Orbitalbelegung unterscheiden sich grundlegend; Beispiele wie MnO4−, FeO4^4−, TiCl4 und TiF6^2− weichen deutlich von 18e ab.","Weil diese Komplexe immer exakt 18 Elektronen besitzen.","Weil hohe Oxidationsstufen keine d-Orbitale besitzen dürfen.","Weil die Regel nur für Hauptgruppenelemente gilt.","Die Folie beschränkt die Regel auf niedrige Oxidationsstufen mit σ-Donor/π-Akzeptor-Liganden.");

// Komplexstabilität, Chelat, Kinetik
t4("Teil 1","Komplexstabilität & Reaktivität","Was bezeichnet die thermische Stabilität eines Komplexes in der Folie?","Die Temperatur der Zersetzung bzw. Ligandabspaltung im Festkörper oder in Lösung.","Die Geschwindigkeit des Ligandenaustauschs bei Raumtemperatur.","Nur die Größe der Bildungsenthalpie.","Die magnetische Stabilität im Feld.","Thermisch ist nicht dasselbe wie thermodynamisch oder kinetisch.");
t4("Teil 1","Komplexstabilität & Reaktivität","Warum können in einer Lösung mehrere MLn-Spezies gleichzeitig vorkommen?","Die Ligandensubstitution erfolgt stufenweise und reversibel; die einzelnen Ki bestimmen die Verteilung.","Weil jede Komplexbildungsreaktion irreversibel bis MLN läuft.","Weil nur ein einziges Ki existiert.","Weil Wasser nie an Metallionen koordiniert.","Mehrere aufeinanderfolgende Gleichgewichte überlagern sich.");
t4("Teil 1","Chelateffekt","Welcher thermodynamische Beitrag erklärt den Chelateffekt nach Schwarzenbach hauptsächlich?","Ein günstiger Entropiebeitrag.","Eine außergewöhnlich große zusätzliche M–N-Bindungsenthalpie.","Eine Verringerung der Elektronenzahl am Metall.","Ausschließlich eine höhere Oxidationsstufe.","Für gleiche Ligatoratome sind ΔH-Beiträge ähnlich.");
t4("Teil 1","Chelateffekt","Warum steigt bei der Bildung von [Ni(en)3]2+ aus [Ni(H2O)6]2+ und en die Entropie?","Drei en-Moleküle verdrängen sechs koordinierte H2O; dadurch entstehen mehr freie Teilchen in Lösung.","Weil alle Wassermoleküle aus der Lösung verschwinden.","Weil en in sechs Einzelmoleküle zerfällt.","Weil das Metallion verdampft.","Mehrzähnige Liganden setzen mehrere Solvensmoleküle frei.");
t4("Teil 1","Chelateffekt","Wie verändert eine größere Zahl an Chelatringen typischerweise die Komplexstabilität?","Der Chelateffekt wird stärker und die Stabilität steigt.","Die Stabilität sinkt zwangsläufig.","Die Zahl der Chelatringe spielt keine Rolle.","Mehr Chelatringe führen immer zu vollständiger Dissoziation.","Makrocyclen werden als besonders stabil genannt.");
t4("Teil 1","Chelateffekt","Welche biologisch relevanten Systeme nennt die Folie als Beispiele stabiler Chelat-/Makrocycluskomplexe?","Chlorophyll, Porphyrine, Cobalamin und Phthalocyanine.","Nur NaCl und KBr.","Nur XeF2 und SF6.","Nur AlCl3 und BF3.","Makrocyclische Chelatoren sind biologisch zentral.");
t4("Teil 1","Komplexanwendungen","Welche analytische Anwendung von Komplexbildung wird mit EDTA verknüpft?","Komplexometrische Titration.","Gaschromatographie.","Radikalpolymerisation.","Elektrolyse von Fluorid.","EDTA ist ein klassischer Chelator.");
t4("Teil 1","Komplexanwendungen","Wie kann Komplexierung bei der Trennung von Metallionen genutzt werden?","Durch Flüssig-Flüssig-Extraktion, wenn Komplexe unterschiedlich zwischen wässriger und organischer Phase verteilt werden.","Nur durch Verdampfen der Metallionen.","Ausschließlich durch magnetische Trennung.","Komplexierung verhindert grundsätzlich jede Phasentrennung.","Die Folie nennt Co/Ni-Extraktion.");
t4("Teil 1","Komplexanwendungen","Welche medizinische Anwendung von Chelatkomplexen wird genannt?","Entfernung toxischer Metallionen bei Schwermetallvergiftungen.","Erzeugung elementaren Fluors im Körper.","Herstellung von Silikonen.","Reduktion von N2 zu NH3.","Chelattherapie.");
t4("Teil 1","Komplexanwendungen","Welche diagnostische Anwendung von Metallkomplexen wird in der Medizin genannt?","Technetium-Komplexe als Radiodiagnostika.","Titan-Komplexe als Röntgenkontrast nur durch Dichte.","Natriumkomplexe als MRT-Kontrast ausschließlich.","Xenonfluoride als Blutmarker.","Ein nuklearmedizinisches Beispiel.");
t4("Teil 1","Substitutionskinetik","Welche d-Konfigurationen nennt die Folie als typische kinetisch labile oktaedrische Fälle?","d1, d2, high-spin d5 und d9.","d3 und low-spin d6.","Nur d10.","Ausschließlich low-spin d8.","Ti3+, V3+, Mn2+/Fe3+ und Cu2+ werden genannt.");
t4("Teil 1","Substitutionskinetik","Welche Metallionen werden als Beispiele für kinetisch inerte low-spin-d6-Komplexe genannt?","Co3+, Ru2+, Rh3+, Ir3+ und Pt4+.","Ti3+, V3+, Mn2+ und Cu2+.","Ag+, Au+ und Zn2+.","Na+, K+ und Mg2+.","Low-spin d6 ist ein Inertheitsmuster.");
t4("Teil 1","Substitutionskinetik","Warum lassen sich bei kinetisch inerten Komplexen geometrische Isomere leichter isolieren?","Der Ligandenaustausch bzw. die Umlagerung ist so langsam, dass die Isomere nicht rasch ineinander übergehen.","Weil sie thermodynamisch immer gleich stabil sind.","Weil keine Liganden vorhanden sind.","Weil ihre Koordinationszahl null ist.","Werner konnte solche Isomere isolieren.");

// Magnetismus und Spektroskopie
t4("Teil 1","Magnetismus","Wie reagiert ein diamagnetischer Stoff auf ein äußeres Magnetfeld?","Er wird schwach aus dem Feld verdrängt.","Er wird stark in das Feld hineingezogen.","Er zeigt ferromagnetische Domänen.","Er besitzt zwingend ungepaarte Elektronen.","Diamagnetismus ist ein kleiner Abstoßungseffekt.");
t4("Teil 1","Magnetismus","Was unterscheidet Ferromagnetismus von gewöhnlichem Paramagnetismus?","Kooperative Wechselwirkungen vieler Elektronen im Festkörper erzeugen einen um Größenordnungen stärkeren Effekt.","Ferromagnetismus tritt nur bei diamagnetischen Molekülen auf.","Ferromagnetismus ist schwächer als Diamagnetismus.","Es gibt keinen Unterschied.","Kooperatives Verhalten ist entscheidend.");
t4("Teil 1","Magnetismus","Welche experimentellen Methoden nennt die Folie zur Bestimmung magnetischer Suszeptibilität bzw. magnetischer Eigenschaften?","Gouy-/Faraday-Magnetwaage, NMR/EPR und SQUID.","Nur UV/Vis-Spektroskopie.","Nur Massenspektrometrie.","Nur Röntgendiffraktion.","Mehrere magnetische Messmethoden werden aufgelistet.");
t4("Teil 1","Spektroskopie","Welche Ursache haben intensive UV-Banden, die auch bei Hauptgruppenkomplexen und freien Liganden auftreten?","Innerligand-Elektronenübergänge.","d–d-Übergänge des Zentralmetalls.","Ausschließlich IVCT.","Nukleare Übergänge.","Diese Banden brauchen keine d-Orbitale.");
t4("Teil 1","Spektroskopie","Warum erscheint ein Übergangsmetallkomplex häufig in der Komplementärfarbe des absorbierten Lichts?","Weißes Licht verliert die absorbierten Wellenlängen; die verbleibende Mischung wird als Komplementärfarbe wahrgenommen.","Der Komplex emittiert immer exakt dieselbe Wellenlänge, die er absorbiert.","Alle Farben entstehen ausschließlich durch Fluoreszenz.","Die Farbe ist unabhängig vom Absorptionsspektrum.","Absorption bestimmt die beobachtete Gegenfarbe.");
t4("Teil 1","Spektroskopie","Was ist der Grundgedanke des Loch-Mechanismus für d9-Systeme?","d10−n kann analog zu n positiven Löchern behandelt werden; die energetische Betrachtung kehrt sich entsprechend um.","d9 wird wie d1 mit identischer Orbitalreihenfolge und ohne Änderung behandelt.","Ein d9-Ion besitzt neun echte Positronen.","Alle d-Orbitale werden entleert.","Die Folie illustriert das an Cu2+.");
t4("Teil 1","Spektroskopie","Warum sind d–d-Absorptionsbanden häufig breit?","M–L-Schwingungen verändern Δ; elektronische Übergänge sind viel schneller als Kernbewegungen, sodass viele Schwingungszustände statistisch beitragen.","Weil d-Orbitale keine diskreten Energien besitzen.","Weil jeder Komplex nur eine einzige starre Geometrie hat.","Weil das Licht während der Schwingung dem Molekül folgt.","Franck–Condon-Prinzip.");
t4("Teil 1","Spektroskopie","Was besagt die Spinauswahlregel für elektronische Übergänge?","ΔS = 0; die Spinmultiplizität soll erhalten bleiben.","ΔS muss immer ±1 sein.","Nur Singulett→Triplett ist erlaubt.","Der Spin spielt keine Rolle.","Multiplizitätserhalt.");
t4("Teil 1","Spektroskopie","Warum können formal Laporte- oder spinverbotene d–d-Übergänge trotzdem schwach beobachtet werden?","Spin-Bahn-Kopplung und vibronische Kopplung können die Verbote teilweise aufweichen.","Weil Auswahlregeln nur für Hauptgruppen gelten.","Weil d–d-Übergänge immer vollständig erlaubt sind.","Nur durch chemische Zersetzung des Komplexes.","Die Folie nennt beide Kopplungsmechanismen.");
t4("Teil 1","Spektroskopie","Welche Lebensdauerzuordnung ist im qualitativen Emissionsschema angegeben?","Der angeregte Singulettzustand S1 ist kurzlebiger, der Triplettzustand T1 langlebiger.","T1 ist immer kurzlebiger als S1.","S0 ist der langlebigste angeregte Zustand.","S1 und T1 haben definitionsgemäß dieselbe Lebensdauer.","Spinverbotene Rückkehr aus T1 verlangsamt die Emission.");
t4("Teil 1","Spektroskopie","Welcher Prozess erzeugt in der OLED-Anwendung mit Iridiumkomplexen die Elektrolumineszenz?","Rekombination injizierter Elektronen und Löcher.","Ausschließlich thermische Zersetzung des Ir-Komplexes.","Oxidation von O2 zu O3.","Ligandenaustausch mit Wasser.","Elektron- und Lochinjektion treffen zusammen.");
