// AMOC Fragentyp 3 – Neue Folienlücken, Teil A
window.AMOC_TYPE4=[];
let T4ID=1;
function t4(part,topic,q,c,w1,w2,w3,hint){
  window.AMOC_TYPE4.push({id:T4ID++,part,topic,q,opts:[
    {t:c,e:"Richtig – diese Aussage wird so in den AMOC-Folien behandelt."},
    {t:w1,e:"Das entspricht nicht der Folienaussage."},
    {t:w2,e:"Diese Zuordnung ist in den Folien nicht so angegeben."},
    {t:w3,e:"Das ist nicht die gesuchte Folieninformation."}
  ],a:0,hint});
}

// Teil 1 – Atombau
t4("Teil 1","Atombau","Welche Elektronenkonfigurations-Anomalie wird für Kupfer ausdrücklich gezeigt?","Cu: 3d10 4s1 statt 3d9 4s2.","Cu: 3d8 4s3 statt 3d10 4s1.","Cu: 3d9 4s2 ist gerade der bevorzugte Grundzustand.","Cu besitzt im Grundzustand keine 4s-Elektronen.","Halb- und vollbesetzte Unterschalen sowie Elektronenwechselwirkungen spielen eine Rolle.");
t4("Teil 1","Atombau","Welche ungewöhnliche Grundzustandskonfiguration wird für Ruthenium in den Folien angegeben?","Ru: 4d7 5s1 statt 4d6 5s2.","Ru: 4d5 5s3 statt 4d7 5s1.","Ru: 4d6 5s2 ohne Ausnahme.","Ru: 4d10 5s0.","Die Folie nennt Ru zusammen mit Cu und Pt als Anomaliebeispiel.");
t4("Teil 1","Atombau","Welche Grundzustands-Anomalie wird für Platin gezeigt?","Pt: 4f14 5d9 6s1 statt 4f14 5d10 6s0.","Pt: 4f14 5d8 6s2 statt 4f14 5d9 6s1.","Pt besitzt 5d10 6s2.","Pt besitzt keine 6s-Beteiligung.","Die energetische Reihenfolge liegt bei schweren Atomen sehr dicht.");
t4("Teil 1","Atombau","Wie viele radiale Knoten besitzen ns-Orbitale laut Folie?","n−1 radiale Knoten.","n radiale Knoten.","n−2 radiale Knoten.","Immer genau einen radialen Knoten.","Vergleiche ns, np und nd.");
t4("Teil 1","Atombau","Wie viele radiale Knoten besitzen np-Orbitale laut Folie?","n−2 radiale Knoten.","n−1 radiale Knoten.","n−3 radiale Knoten.","Keine radialen Knoten unabhängig von n.","Die Zahl sinkt gegenüber ns um eins.");
t4("Teil 1","Atombau","Welche Reihenfolge der Abschirmung innerer Unterschalen wird auf der Folie angegeben?","s schirmt effektiver als p, p effektiver als d, d effektiver als f.","f > d > p > s.","p > s > f > d.","Alle Unterschalen schirmen gleich gut.","Durchdringung zum Kern ist entscheidend.");
t4("Teil 1","Atombau","Welchen Einfluss hat eine steigende effektive Kernladung von Li nach F auf 2s und 2p?","Der Energieabstand zwischen 2s und 2p wird größer; 2s wird stärker beeinflusst.","2s und 2p bleiben exakt gleich weit auseinander.","Der Abstand wird kleiner, weil 2p stärker stabilisiert wird.","Nur 2p ändert seine Energie.","s-Orbitale dringen stärker zum Kern vor.");
t4("Teil 1","Atombau","Welche Aussage zur Elektronenaffinität entspricht der Vorlesungs-Konvention?","Ein negativer Wert bedeutet, dass bei Y + e− → Y− Energie frei wird.","Ein positiver Wert bedeutet immer Energieabgabe bei Elektronenaufnahme.","Elektronenaffinität wird nur für Kationen definiert.","Eingeklammerte Werte gehören zur ersten Ionisation.","Achte auf das Vorzeichen in der Folientabelle.");
t4("Teil 1","Atombau","Wofür stehen die eingeklammerten Elektronenaffinitätswerte in der Folie?","Für die zweite Elektronenaufnahme Y− + e− → Y2−.","Für die erste Ionisation Y → Y+ + e−.","Für den Übergang Y2− → Y− + e−.","Für die Elektronegativität.","Es geht um das Hinzufügen eines Elektrons zu einem bereits negativen Ion.");
t4("Teil 1","Atombau","Welche Größenordnung gilt qualitativ für Radius von Anion, neutralem Atom und Kation desselben Elements?","r(Anion) > r(Atom) > r(Kation).","r(Kation) > r(Atom) > r(Anion).","r(Atom) > r(Anion) > r(Kation).","Alle drei Radien sind praktisch identisch.","Elektronenabstoßung und effektive Kernladung ändern sich.");
t4("Teil 1","Atombau","Wie verläuft der Radius in der isoelektronischen Reihe N3−, O2−, F−, Ne, Na+, Mg2+, Al3+?","Er nimmt mit steigender Kernladung kontinuierlich ab.","Er nimmt mit steigender Kernladung kontinuierlich zu.","Er bleibt wegen gleicher Elektronenzahl konstant.","Er ist bei Ne am größten.","Gleiche Elektronenzahl, aber unterschiedliche Protonenzahl.");
t4("Teil 1","Atombau","Was ist die Ursache der Lanthanoidenkontraktion, wie sie in den Folien erklärt wird?","f-Orbitale schirmen schlecht, dadurch steigt Zeff stark und 5d-Elemente werden unerwartet klein.","f-Orbitale schirmen besonders stark und blähen 5d-Elemente auf.","Die 5d-Orbitale verschwinden vollständig.","Sie entsteht durch höhere Elektronenaffinität der Halogene.","Schlechte Abschirmung durch f-Elektronen.");
t4("Teil 1","Atombau","Welche überraschende Konsequenz der Lanthanoidenkontraktion wird mit Zr und Hf illustriert?","Zr4+ und Hf4+ besitzen sehr ähnliche Ionenradien.","Hf4+ ist etwa doppelt so groß wie Zr4+.","Zr4+ ist deutlich größer als alle 5d-Ionen.","Hf4+ ist kleiner als Ti4+ um mehrere Hauptschalen.","4d/5d-Homologe werden größenmäßig ähnlich.");

// Teil 1 – Lewis/VSEPR/Zeichnen
t4("Teil 1","Lewis & Struktur","Was ist der erste Schritt des in der Vorlesung gezeigten Lewis-Algorithmus?","Die Konnektivität festlegen; H ist terminal und meist steht das weniger elektronegative Element zentral.","Zuerst alle formalen Ladungen auf null setzen.","Zuerst Hybridisierung bestimmen.","Zuerst die Punktgruppe bestimmen.","Lewis beginnt mit dem Atomgerüst.");
t4("Teil 1","Lewis & Struktur","Welche Aussage macht die Folie zur Konnektivität bei Lewis-Formeln?","Sie lässt sich nicht immer eindeutig aus der Summenformel ableiten; Isomere müssen berücksichtigt werden.","Sie folgt immer eindeutig aus der Elektronegativität.","Bei gleicher Summenformel gibt es nie verschiedene Konstitutionen.","Sie ist für Lewis-Formeln bedeutungslos.","Chemisches Wissen/Intuition kann nötig sein.");
t4("Teil 1","Lewis & Struktur","Welche Lewis-Alternative soll bei mehreren möglichen Formeln bevorzugt werden?","Viele Mehrfachbindungen, geringe Häufung formaler Ladungen und viele mesomere Permutationen bei gleicher Konnektivität.","Maximal viele formale Ladungen unabhängig von Elektronegativität.","Möglichst nur Einfachbindungen, auch wenn Oktette verletzt werden.","Immer die Struktur mit der höchsten Gesamtladung.","Das ist die Folienregel für die Registrierformel.");
t4("Teil 1","Lewis & Struktur","Was können Lewis-Formeln laut Folie nur eingeschränkt leisten?","Alternative Konstitutionen bewerten und reale Bindungsverhältnisse bzw. 3D-Struktur eindeutig beschreiben.","Valenzelektronen zählen.","Formale Ladungen darstellen.","Atomverknüpfungen skizzieren.","Lewis ist ein Elektronenbuchhaltungsmodell.");
t4("Teil 1","Konformation","Welche Konformation ist für Hydrazin N2H4 laut Folie das Energieminimum?","Eine gauche-Konformation.","Die exakt ekliptische Konformation.","Eine streng planare trans-Konformation.","Eine lineare N–N–H-Anordnung.","Die Folie kontrastiert Hydrazin mit Ethan.");
t4("Teil 1","Koordinationspolyeder","Welche zusätzliche KZ=4-Geometrie wird neben tetraedrisch und quadratisch-planar gezeigt?","Disphenoid bzw. Sägebock.","Pentagonal-bipyramidal.","Quadratisch-antiprismatisch.","Oktaedrisch.","Die Tabelle enthält drei KZ=4-Formen.");
t4("Teil 1","Koordinationspolyeder","Welche Standardgeometrie ist in der Polyedertabelle für KZ=7 angegeben?","Pentagonal-bipyramidal.","Dreifach überkappt trigonal-prismatisch.","Quadratisch-antiprismatisch.","Trigonal-planar.","Sieben Ecken um das Zentralatom.");
t4("Teil 1","Koordinationspolyeder","Welche Standardgeometrie wird für KZ=8 in der Grundlagenfolie gezeigt?","Quadratisch-antiprismatisch.","Kubisch ausschließlich.","Pentagonal-bipyramidal.","Oktaedrisch.","Die Tabelle zeigt das quadratische Antiprisma.");
t4("Teil 1","VSEPR","Welche Struktur ergibt das in der Folientabelle angegebene Muster Y2EX5?","Pentagonal-planar.","T-förmig.","Quadratisch-pyramidal.","Oktaedrisch.","Zwei freie Elektronenpaare werden bei der Formbenennung weggelassen.");
t4("Teil 1","VSEPR","Welche Struktur ergibt das in der Tabelle angegebene Muster YEX6?","Überkappt-oktaedrisch.","Pentagonal-bipyramidal.","Quadratisch-planar.","Trigonal-bipyramidal.","Ein freies Elektronenpaar zusätzlich zu sechs Bindungspartnern.");
t4("Teil 1","VSEPR","Welche Struktur ergibt das Muster YEX8 in der Folientabelle?","Überkappt quadratisch-antiprismatisch.","Ikosaedrisch.","Pentagonal-planar.","Kubisch ohne Überkappung.","Acht Bindungspartner plus ein freies Elektronenpaar.");
t4("Teil 1","VSEPR","Welche allgemeine VSEPR-Regel gilt für Mehrfachbindungen gegenüber Einfachbindungen?","Mehrfachbindungen benötigen mehr Raum.","Mehrfachbindungen benötigen weniger Raum als freie Elektronenpaare und Einfachbindungen immer gleich viel.","Mehrfachbindungen beeinflussen die Geometrie nicht.","Mehrfachbindungen werden im VSEPR nicht als Elektronendomänen betrachtet.","Höhere Elektronendichte verstärkt Abstoßung.");
t4("Teil 1","Polyeder & Zeichnen","Welche Bedeutung haben Kanten und Flächen in einer reinen Koordinationspolyeder-Darstellung zunächst?","Sie kennzeichnen die geometrische Koordinationsumgebung und bedeuten nicht automatisch chemische Bindungen.","Jede Kante ist zwingend eine kovalente Bindung.","Jede Fläche entspricht einem delokalisierten π-System.","Sie stellen ausschließlich Wasserstoffbrücken dar.","Polyeder sind geometrische Hilfsdarstellungen.");
t4("Teil 1","Polyeder & Zeichnen","Wie kann man die P4O10-Struktur aus einem P4-Tetraeder konstruieren?","Alle P–P-Kanten mit O überbrücken und an jedem P zusätzlich ein terminales O setzen.","Nur ein O in das Zentrum des P4-Tetraeders setzen.","Jede P–P-Kante durch eine P=P-Doppelbindung ersetzen.","Vier P4-Tetraeder direkt kantenverknüpfen.","Die Folie leitet P4O10 ausdrücklich aus P4 ab.");
t4("Teil 1","Polyeder & Zeichnen","Was wird aus jeder Dreiecksfläche des ursprünglichen P4-Tetraeders in P4O10?","Ein P3O3-Sechsring in Sesselkonformation.","Ein P3-Dreiring ohne Sauerstoff.","Ein PO4-Tetraeder ohne Ring.","Ein quadratischer P2O2-Ring.","Jede P–P-Kante wurde durch O erweitert.");
t4("Teil 1","Polyoxometallate","Wie ist [W6O19]2− in der Polyederdarstellung aufgebaut?","Sechs verknüpfte WO6-Oktaeder bilden einen Superoktaeder.","Sechs isolierte WO4-Tetraeder ohne gemeinsame O-Atome.","Ein W6-Ring aus linearen WO2-Einheiten.","Ein Ikosaeder aus zwölf WO6-Einheiten.","Die Folie nennt ausdrücklich einen Superoktaeder.");
t4("Teil 1","Polyoxometallate","Welche besondere gemeinsame Brücke besitzen alle sechs WO6-Oktaeder in [W6O19]2−?","Ein gemeinsames μ6-O-Atom im Zentrum.","Sechs verschiedene terminale μ1-O-Atome.","Eine gemeinsame W–W-Bindung ohne Sauerstoff.","Ein μ2-Hydrid.","Alle sechs Oktaeder teilen eine Spitze.");
t4("Teil 1","Polyoxometallate","Welche Kondensationsgleichung wird für [W6O19]2− angegeben?","6 WO4^2− + 10 H+ → [W6O19]^2− + 5 H2O.","6 WO3 + O2 → [W6O19]^2−.","W6 + 19 O2− → [W6O19]^2−.","6 H2WO4 → [W6O19]^2− + H2.","Wolframat kondensiert unter Protonierung.");
t4("Teil 1","Polyoxometallate","Wie definiert die Folie Polyoxometallate (POM) qualitativ?","Aus mindestens drei Übergangsmetall-Oxoanionen aufgebaute, O-verbrückte große geschlossene 3D-Netzwerke/Cluster.","Nur aus zwei Hauptgruppenoxiden bestehende lineare Moleküle.","Reine Metallcluster ohne Sauerstoff.","Ausschließlich organische Polymere mit Metallionen.","Vanadat, Molybdat und Wolframat werden als Beispiele genannt.");
t4("Teil 1","Polyoxometallate","Welches Polyoxometallat entsteht beim in der Folie gezeigten Phosphatnachweis mit Ammoniummolybdat?","[PMo12O40]3− als gelber Niederschlagsspezies.","[PW6O19]2−.","[P2MoO7]4−.","[MoO4]2− bleibt unverändert und löslich.","Ein zentraler PO4-Tetraeder wird von Mo-O-Einheiten umgeben.");
