// AMOC Fragentyp 3 – Neue Folienlücken, Teil B

// Symmetrie
t4("Teil 1","Symmetrie","Wie ist eine horizontale Spiegelebene σh definiert?","Sie steht senkrecht zur höchsten Drehachse.","Sie enthält die höchste Drehachse.","Sie halbiert stets den Winkel zwischen zwei C2-Achsen.","Sie ist identisch mit einem Inversionszentrum.","Horizontal bezieht sich auf die Hauptdrehachse.");
t4("Teil 1","Symmetrie","Wie ist eine vertikale Spiegelebene σv definiert?","Sie enthält die höchste Drehachse.","Sie steht senkrecht zur höchsten Drehachse.","Sie enthält grundsätzlich keine Drehachse.","Sie existiert nur in linearen Molekülen.","Vergleiche σh und σv.");
t4("Teil 1","Symmetrie","Was kennzeichnet eine diagonale Spiegelebene σd?","Sie enthält die Hauptdrehachse und halbiert den Winkel zwischen zwei C2-Achsen.","Sie steht immer senkrecht zur Hauptdrehachse.","Sie ist eine Ebene ohne Beziehung zu Rotationsachsen.","Sie entspricht einer Drehspiegelachse.","XeF4 ist das Folienbeispiel.");
t4("Teil 1","Symmetrie","Aus welchen zwei Operationen besteht eine Drehspiegeloperation Sn?","Rotation um 360°/n und anschließende Spiegelung an einer Ebene senkrecht zur Drehachse.","Rotation und anschließende Inversion im Zentrum.","Zwei aufeinanderfolgende Spiegelungen an parallelen Ebenen.","Nur eine Rotation um 180°.","Sn ist eine zusammengesetzte Operation.");
t4("Teil 1","Symmetrie","Was ergibt die dreifache sukzessive Anwendung einer C3-Operation?","Die Identitätsoperation E.","Eine C2-Operation.","Eine Spiegelung σh.","Eine Inversion i.","Drei Rotationen um 120° ergeben 360°.");
t4("Teil 1","Symmetrie","Was ist die Identitätsoperation E?","Die Operation, die das Molekül unverändert lässt; sie ist äquivalent zu C1.","Eine Spiegelung an jeder vorhandenen Ebene.","Eine Inversion aller Atome.","Eine Rotation ausschließlich bei linearen Molekülen.","Jede Punktgruppe enthält E.");
t4("Teil 1","Symmetrie","Welche vollständige Punktgruppe gehört zum regulären Tetraeder und wird mit P4 illustriert?","Td.","D3h.","Oh.","Ih.","P4 ist ein Polyedergruppen-Beispiel.");
t4("Teil 1","Symmetrie","Welche Punktgruppe wird für W(CO)6 als ideales oktaedrisches Beispiel angegeben?","Oh.","Td.","D4h.","C4v.","Sechs äquivalente Liganden im Oktaeder.");
t4("Teil 1","Symmetrie","Welche Punktgruppe wird für das closo-Boran [B12H12]2− als Ikosaederbeispiel angegeben?","Ih.","Oh.","Td.","D3d.","Die Folie ordnet die drei platonischen Polyedergruppen zu.");
t4("Teil 1","Symmetrie","Wann gehört eine Molekülpunktgruppe zu den sogenannten Polyedergruppen?","Wenn sie mindestens zwei Drehachsen mit Zähligkeit größer als zwei besitzt.","Wenn sie genau eine C2-Achse besitzt.","Nur wenn ein Inversionszentrum vorhanden ist.","Nur wenn das Molekül planar ist.","Diese Gruppen entsprechen den Symmetrien platonischer Körper.");
t4("Teil 1","Symmetrie","Was steht in einer Charaktertafel in der linken Spalte?","Die irreduziblen Darstellungen der Punktgruppe.","Die Atomnummern der beteiligten Elemente.","Nur die Bindungslängen.","Die Oxidationszahlen aller Atome.","Die Kopfzeile enthält dagegen Punktgruppe und Symmetrieoperationen.");
t4("Teil 1","Symmetrie","Was bedeuten in einer Charaktertafel die Charaktere +1 und −1 qualitativ?","+1 bedeutet symmetrisches, −1 antisymmetrisches Verhalten bezüglich der Operation.","+1 bedeutet bindend, −1 antibindend.","+1 bedeutet gerade, −1 immer ungerade gegenüber Inversion.","Sie geben direkt die Elektronenzahl an.","Es geht um das Verhalten unter einer Symmetrieoperation.");

// Kovalente Bindung / MO
t4("Teil 1","Kovalente Bindung","Wie beschreibt das VB-Konzept eine heteronukleare Bindung qualitativ genauer als eine rein kovalente Struktur?","Als Resonanz bzw. Mischung aus kovalenten und ionischen Elektronenverteilungen.","Als ausschließlich ionische Bindung.","Als reine Metallbindung.","Als Überlagerung nur antibindender Atomorbitale.","Die Folie zeigt unpolare und polare Grenzanteile.");
t4("Teil 1","Kovalente Bindung","Welche Symmetrieeigenschaft besitzt eine σ-Bindung bezüglich ihrer Bindungsachse?","Sie ist rotationssymmetrisch um die Bindungsachse.","Sie besitzt zwingend eine Knotenebene durch die Bindungsachse.","Sie ist nur bei 180° Rotation invariant.","Sie ist immer antisymmetrisch bezüglich der Bindungsachse.","Vergleiche σ und π.");
t4("Teil 1","Kovalente Bindung","Warum werden klassische Mehrfachbindungen bei schweren Hauptgruppenelementen zunehmend schwieriger?","Schlechtere Hybridisierung und schlechtere s/p- bzw. p/p-Überlappung; Donor-Akzeptor-Anteile werden wichtiger.","Weil schwere Elemente keine p-Orbitale besitzen.","Weil ihre Valenzorbitale kleiner als 2p-Orbitale werden.","Weil Elektronegativität allein Mehrfachbindungen verbietet.","Größere diffuse Orbitale überlappen schlechter.");
t4("Teil 1","Kovalente Bindung","Welche Reihenfolge der Orbitalüberlappungsstärke ist in der Folie angegeben?","p << sp3 < sp2 < sp.","sp < sp2 < sp3 < p.","sp3 > sp > p > sp2.","Alle Hybridisierungen überlappen gleich stark.","Mehr s-Charakter verbessert gerichtete Überlappung.");
t4("Teil 1","MO & LGO","Welche qualitative Besonderheit zeigt das MO-Bild von H2O im Vergleich zum einfachen sp3-VB-Modell?","Es enthält vier unterschiedliche, ungerichtete bzw. delokalisierte MOs statt vier identischer sp3-Hybridorbitale.","Es liefert vier identische gerichtete MOs.","Es besitzt keine freien Elektronenpaare.","Es sagt eine lineare Struktur voraus.","MO und VB verteilen die Elektronendichte unterschiedlich.");
t4("Teil 1","MO & LGO","Wie wird das oberste freie Elektronenpaar im qualitativen H2O-MO-Schema beschrieben?","Als praktisch nicht O–H-bindendes MO, also ein weitgehend freies Elektronenpaar.","Als stark O–H-antibindendes Orbital.","Als vollständig bindendes σ-MO.","Als leeres LUMO.","Die Folie unterscheidet stark, schwach und nicht bindende Beiträge.");
t4("Teil 1","MO & LGO","Wie viele Ligandengruppenorbitale entstehen insgesamt aus allen p-Orbitalen der sechs F-Atome in SF6?","24 LGOs.","6 LGOs.","12 LGOs.","18 LGOs.","Jedes F liefert mehrere p-Funktionen.");
t4("Teil 1","MO & LGO","Welche zwei Arten von F-p-Orbitalen werden beim SF6-MO-Schema unterschieden?","Radiale und tangentiale p-Orbitale.","Bindende und ionische p-Orbitale.","Nur px und py ohne geometrische Unterscheidung.","Hybridisierte und nicht hybridisierte d-Orbitale.","Die Ausrichtung relativ zur S–F-Achse ist entscheidend.");
t4("Teil 1","MO & LGO","Welche Aussage macht das s/p-Basissatz-MO-Schema zu den sechs S–F-Wechselwirkungen in SF6?","Von sechs relevanten MOs sind vier bindend und zwei nichtbindend.","Alle sechs sind gleich stark bindend.","Drei sind bindend und drei antibindend besetzt.","Es entstehen ausschließlich nichtbindende MOs.","Das erklärt die mittlere Bindungsordnung kleiner als eins.");
t4("Teil 1","MO & LGO","Welche mittlere S–F-Bindungsordnung ergibt das in der Folie gezeigte SF6-MO-Modell?","4/6, also ungefähr 0,67 pro S–F-Bindung.","Genau 2 pro S–F-Bindung.","6/4, also 1,5.","Genau 1 für jede S–F-Bindung.","Vier bindende Beiträge werden auf sechs Bindungen verteilt.");
t4("Teil 1","MO & LGO","Welche Schlussfolgerung zieht die SF6-Folie bezüglich einer echten Oktettüberschreitung im s/p-Basissatz?","Eine lokale Oktettüberschreitung am S ist aus Symmetriegründen nicht nötig bzw. im s/p-Modell nicht möglich.","S muss sechs d-Orbitale vollständig besetzen.","SF6 ist deshalb rein ionisch.","Die Oktettregel verlangt sechs klassische 2c2e-S–F-Bindungen.","Das delokalisierte MO-Modell ersetzt das erweiterte Oktettbild.");

// Komplexchemie Grundlagen
t4("Teil 1","Komplexchemie Grundlagen","Wie definiert die Vorlesung die Oxidationszahl eines Zentralmetalls formal?","Als Ladung nach hypothetischer heterolytischer Spaltung aller M–L-Bindungen, wobei L die Bindungselektronen erhält.","Als Zahl aller direkt gebundenen Ligatoratome.","Als Ladung nach homolytischer Spaltung aller Bindungen.","Als Anzahl der d-Elektronen.","Nicht mit formaler Ladung oder KZ verwechseln.");
t4("Teil 1","Komplexchemie Grundlagen","Wie wird die formale Ladung im Vergleich zur Oxidationszahl konzeptionell erhalten?","Durch hypothetische homolytische Spaltung der M–L-Bindungen.","Durch heterolytische Spaltung mit allen Elektronen am Liganden.","Durch Zählen der Koordinationszahl.","Durch Entfernen aller d-Elektronen.","Homolytisch versus heterolytisch.");
t4("Teil 1","Komplexchemie Grundlagen","Welche Geometrie wird für KZ=9 am Beispiel [Ln(H2O)9]3+ bzw. ReH9^2− angegeben?","Dreifach überkapptes trigonales Prisma.","Quadratisch-antiprismatisch.","Ikosaedrisch.","Pentagonal-bipyramidal.","Neun Koordinationsplätze.");
t4("Teil 1","Komplexchemie Grundlagen","Welche Geometrie wird für KZ=10 bei [M(NO3)5]2− angegeben?","Zweifach überkapptes quadratisches Antiprisma.","Dreifach überkapptes trigonales Prisma.","Ikosaeder.","Oktaeder.","Zehn Koordinationsplätze.");
t4("Teil 1","Komplexchemie Grundlagen","Welche Geometrie wird für KZ=12 bei [M(NO3)6]3− bzw. Zr(BH4)4 angegeben?","Ikosaedrisch.","Kubisch.","Dodekaedrisch.","Hexagonal-planar.","Zwölf Ligatorpositionen.");
t4("Teil 1","Komplexchemie Grundlagen","Welche Kombination begünstigt besonders hohe Koordinationszahlen?","Großes Zentralatom, kleine Liganden und geringe sterische Abstoßung.","Kleines Zentralatom und sehr sperrige Liganden.","Nur starke π-Akzeptorliganden.","Ausschließlich d10-Konfiguration.","Sterik ist für hohe KZ zentral.");
t4("Teil 1","Komplexchemie Grundlagen","Welche Metallionen nennt die Zusammenfassung als typische KZ=6-oktaedrische Fälle?","Cr(III), Co(III) und Pt(IV).","Pt(II), Pd(II) und Au(I).","Ag(I), Au(I) und Cu(I).","Zn(II), Cd(II) und Hg(II) ausschließlich linear.","Die Folie nennt bevorzugte KZ/Polyeder.");
t4("Teil 1","Komplexchemie Grundlagen","Welche Metallionen werden als typische quadratisch-planare KZ=4-Fälle genannt?","Pt(II), Pd(II) und häufig Cu(II).","Cr(III), Co(III) und Pt(IV).","Na(I), K(I) und Rb(I).","Ti(IV), V(V) und Cr(VI) ausschließlich.","d8-Metalle sind klassische Beispiele.");
t4("Teil 1","Komplexchemie Grundlagen","Wie lautet der Name von [MoBr(CO)5] in der Folie?","Bromidopentacarbonylmolybdän(I).","Pentabromidocarbonylmolybdän(V).","Bromidomolybdatpentacarbonyl(0).","Molybdänbromidpentoxid.","Ein Nomenklaturbeispiel aus der Vorlesung.");
t4("Teil 1","Komplexchemie Grundlagen","Wie wird Na2[Fe(CO)4] in der Folie benannt?","Dinatriumtetracarbonylferrat(−II).","Natriumeisentetracarbonyl(II).","Dinatriumtetraoxidoferrat(II).","Tetracarbonyldinatriumferrat(0).","Anionischer Carbonylkomplex mit negativer Oxidationszahl.");
t4("Teil 1","Liganden","Welche Anwendungen werden für [Ru(bipy)3]2+ hervorgehoben?","Photoredoxchemie/Photosensibilisierung, künstliche Photosynthese und Grätzel-Zellen.","Nur Ziegler–Natta-Polymerisation.","Ausschließlich Chlor-Alkali-Elektrolyse.","Nur als Fällungsreagenz für Halogenide.","Die Folie betont Lichtchemie.");
t4("Teil 1","HSAB","Welche der folgenden Spezies wird in der Folie als harte Lewis-Säure eingeordnet?","CO2.","Ag+.","Br2.","S2−.","Die HSAB-Tabelle enthält auch Hauptgruppenmoleküle.");
t4("Teil 1","HSAB","Welche der folgenden Spezies wird in der Folie als weiche Lewis-Base eingeordnet?","CN−.","F−.","OH−.","NH3.","Vergleiche harte und weiche Basen der Tabelle.");
t4("Teil 1","Isomerie","Was ist Brückenisomerie bei Komplexen?","Unterschiedliche Art, wie ein Ligand zwischen mehreren Metallzentren verbrückt.","Unterschiedliche Bindung desselben ambidenten Liganden über verschiedene Atome.","Austausch von Gegenion und koordiniertem Ion.","Bild-Spiegelbild-Isomerie.","Sie ist eine Konstitutionsisomerie eigener Art.");
t4("Teil 1","Isomerie","Was beschreibt Ionen- bzw. Hydratisomerie?","Unterschiedliche Verteilung von Ionen bzw. H2O zwischen innerer und äußerer Koordinationssphäre.","Nur cis/trans-Anordnung zweier Liganden.","Unterschiedliche Konformation eines Chelatrings.","Bindung über verschiedene Ligatoratome desselben Liganden.","Werner-Komplexe liefern klassische Beispiele.");
t4("Teil 1","Isomerie","Welches formale Symmetriekriterium nennt die Folie für Chiralität?","Ein chirales Molekül besitzt keine Drehspiegelachse Sn.","Ein chirales Molekül muss ein Inversionszentrum besitzen.","Ein chirales Molekül muss mindestens eine σ-Ebene besitzen.","Nur Moleküle der Punktgruppe Oh können chiral sein.","Sn umfasst auch i und σ als Spezialfälle.");
t4("Teil 1","Koordinationspolymere","Welche Verbindung wird als gemischtvalentes Preußischblau-artiges Cyanidnetzwerk angegeben?","K[FeII FeIII(CN)6].","K4[FeII(CN)6] ohne weiteres Fe.","Fe(CO)5.","[Fe(H2O)6]3+.","FeII und FeIII sind gleichzeitig vorhanden.");
t4("Teil 1","MOFs","Wie lautet die Formel von MOF-5 in der Folie?","[Zn4O(bdc)3].","[Fe4O(CN)6].","[Cu2(bipy)3].","[Zr6O19]2−.","bdc ist der organische Linker.");
t4("Teil 1","MOFs","Wofür steht bdc in MOF-5?","1,4-Benzoldicarboxylat (Terephthalat).","2,2'-Bipyridin.","Cyclopentadienyl.","Acetylacetonat.","Der Linker verbindet Zn4O-Knoten.");
t4("Teil 1","MOFs","Welche strukturelle Eigenschaft von MOF-5 wird besonders hervorgehoben?","Sehr hohe innere Oberfläche und ein großer leerer Porenanteil.","Es ist ein vollständig dichter unporöser Kristall.","Es besitzt ausschließlich eindimensionale Metallketten ohne Hohlräume.","Es ist ein molekulares Gas.","MOFs werden gerade wegen ihrer Porosität diskutiert.");
