// AMOC Fragentyp 3 – Neue Folienlücken, Teil E

// Gruppe 16
t4("Teil 2","Gruppe 16","Welches technische Verfahren wird für die industrielle Herstellung von H2O2 genannt?","Das Anthrachinon-Verfahren.","Das Haber-Bosch-Verfahren.","Das Siemens-Verfahren.","Die Chlor-Alkali-Elektrolyse.","Anthrachinon wirkt im Redoxkreislauf.");
t4("Teil 2","Gruppe 16","Welche Molekülkonformation besitzt H2O2 laut Folie?","Eine nicht-planare gauche-Struktur.","Eine exakt planare trans-Struktur.","Eine lineare O–O–H-Anordnung.","Eine quadratisch-planare Struktur.","Lone-pair-Abstoßung und Hyperkonjugation werden genannt.");
t4("Teil 2","Gruppe 16","Welche Oxidationsstufe besitzt Sauerstoff in H2O2?","−I.","−II.","0.","+II.","Peroxid liegt zwischen O2 und H2O.");
t4("Teil 2","Gruppe 16","Wie lässt sich die Dichteanomalie von Eis gegenüber flüssigem Wasser erklären?","Das geordnete H-Brückennetzwerk des Eises enthält Hohlräume; in flüssigem Wasser können Moleküle dichter packen.","Eis besitzt keine Wasserstoffbrücken.","Flüssiges Wasser bildet ein starres offenes Gitter.","Eis enthält weniger H2O-Moleküle pro mol.","Offenes Kristallgitter versus dynamisches Netzwerk.");
t4("Teil 2","Gruppe 16","Wie viele Wasserstoffbrücken kann ein H2O-Molekül im idealisierten Netzwerk maximal ausbilden?","Bis zu vier.","Nur eine.","Genau zwei und nie mehr.","Sechs.","Zwei H-Donoren und zwei Lone-Pair-Akzeptoren.");
t4("Teil 2","Gruppe 16","Welche Oxidationsstufe besitzt O in OF2?","+II.","−II.","0.","+I.","F ist elektronegativer als O.");
t4("Teil 2","Gruppe 16","Welche Oxidationsstufe besitzt jedes O in O2F2 formal?","+I.","−I.","0.","+II.","Die Gesamtladung ist null und F jeweils −I.");
t4("Teil 2","Gruppe 16","Welches Element kann laut Folie Sauerstoff zu positiven Oxidationsstufen oxidieren?","Fluor.","Chlor.","Schwefel.","Stickstoff.","Nur F ist elektronegativer als O.");
t4("Teil 2","Gruppe 16","Welche Reaktion zeigt die Hydrolyse von Cl2O?","Cl2O + H2O → 2 HOCl.","Cl2O + H2O → 2 HCl + O2.","Cl2O ist wasserstabil.","Cl2O + H2O → HClO3 + HCl.","Cl2O ist das Anhydrid der hypochlorigen Säure.");
t4("Teil 2","Gruppe 16","Was geschieht beim Erhitzen von S8 zunächst strukturell?","Der Ring öffnet sich und lange catena-S∞-Ketten können entstehen.","S8 zerfällt direkt vollständig zu S-Atomen.","Es entsteht ausschließlich SO2.","Der Ring wird kleiner zu S2 ohne Polymerisation.","Plastischer Schwefel enthält lange Ketten.");
t4("Teil 2","Gruppe 16","Welche Form des Schwefels ist unter Normalbedingungen thermodynamisch am stabilsten?","S8.","Plastischer catena-S∞.","S2.","S20 ausschließlich.","Die Folie betont S8 als stabile Normalform.");
t4("Teil 2","Gruppe 16","Wie beeinflusst das Sauerstoffangebot die Oxidation von H2S?","Bei begrenztem O2 kann S entstehen; bei O2-Überschuss wird weiter zu SO2 oxidiert.","Unabhängig vom O2-Angebot entsteht immer nur SO3.","H2S kann durch O2 nicht oxidiert werden.","Bei O2-Überschuss entsteht ausschließlich H2.","Zwei Reaktionsgleichungen werden gegenübergestellt.");
t4("Teil 2","Gruppe 16","Welche Struktur besitzt SO2 laut Folie?","Gewinkelt und mesomeriestabilisiert.","Linear ohne Resonanz.","Trigonal-planar.","Tetraedrisch.","SO2 ist nicht das strukturelle Analog zu CO2.");
t4("Teil 2","Gruppe 16","In welcher Form liegt 'schweflige Säure' in Wasser überwiegend vor?","Überwiegend als HSO3−-Spezies im SO2/Wasser-System.","Ausschließlich als isoliertes H2SO3-Molekül.","Als SO4^2−.","Als elementarer Schwefel.","Die Folie weist ausdrücklich auf HSO3− hin.");
t4("Teil 2","Gruppe 16","Welche Reaktion zeigt die reduktive Seite von SO2(+IV)?","SO2 + 2 H2S → 3 S + 2 H2O.","2 SO2 + O2 → 2 SO3.","SO2 + H2O → H2SO4.","SO2 + Cl2 → SO3 + 2 HCl.","SO2(+IV) wird zu S(0) reduziert.");
t4("Teil 2","Gruppe 16","Welche klassische Dehydratisierungsreaktion von konzentrierter H2SO4 wird gezeigt?","C12H22O11 → 12 C + 11 H2O.","C12H22O11 + O2 → CO2 ohne Wasser.","H2SO4 hydriert Zucker zu Methan.","Zucker löst sich ohne Reaktion.","Konzentrierte Schwefelsäure entzieht organischem Material Wasser.");
t4("Teil 2","Gruppe 16","Welche Düngemittelreaktion mit H2SO4 wird in der Gruppe-16-Folie gezeigt?","Ca3(PO4)2 + 2 H2SO4 → Ca(H2PO4)2 + 2 CaSO4.","Ca3(PO4)2 + H2SO4 → CaSO4 + PH3.","CaCO3 + H2SO4 → Ca(H2PO4)2.","Na3PO4 + H2SO4 → P4.","Schwerlösliches Rohphosphat wird pflanzenverfügbarer.");
t4("Teil 2","Gruppe 16","Welche Struktur besitzt S2Cl2 laut Folie?","Eine nicht-planare Struktur.","Eine exakt lineare Struktur.","Ein quadratisch-planarer Ring.","Ein ionisches NaCl-artiges Gitter.","Die S–S-Kette ist verdreht.");
t4("Teil 2","Gruppe 16","Welche moderne Materialanwendung wird für CdSe hervorgehoben?","Halbleiter/Quantenpunkte mit größenabhängiger Emission.","Hochspannungs-Isoliergas.","Katalysator des Kontaktverfahrens.","Wasserstoffspeicher.","CdSe-Quantenpunkte ändern ihre Emissionsfarbe mit der Größe.");
t4("Teil 2","Gruppe 16","Welche Anwendung wird für Bi2Te3 genannt?","Thermoelektrisches Material zur Umwandlung von Wärme in Elektrizität.","Starkes Fluorierungsmittel.","Photoredoxfarbstoff.","Kronenether.","Seebeck-Effekt.");
t4("Teil 2","Gruppe 16","Welche biologische Bedeutung besitzt Selenocystein?","Es ist die 21. proteinogene Aminosäure und Bestandteil von Redoxenzymen.","Es ist ein Halogenierungsreagenz.","Es ist ein anorganisches Düngemittel.","Es ist ein Edelgas-Clathrat.","Selen als essentielles Spurenelement.");

// Gruppe 17/18
t4("Teil 2","Gruppen 17 & 18","Wie wird elementares Fluor technisch hergestellt?","Durch Elektrolyse von KF·xHF-Schmelzen.","Durch direkte Oxidation von Wasser mit O2.","Durch Haber-Bosch-Synthese.","Durch Destillation von NaF in Wasser.","Wasserfreie Fluorid/HF-Schmelzen sind nötig.");
t4("Teil 2","Gruppen 17 & 18","Welches technische Verfahren liefert Chlor?","Chlor-Alkali-Elektrolyse.","Anthrachinon-Verfahren.","Kontaktverfahren.","Siemens-Prozess.","NaCl-Sole wird elektrolysiert.");
t4("Teil 2","Gruppen 17 & 18","Welche chemische Route zur Chlordarstellung nennt die Folie neben der Elektrolyse?","Oxidation von HCl.","Reduktion von HCl mit H2.","Hydrolyse von NaCl.","Zersetzung von NH4Cl ohne Oxidationsmittel.","Chlorid muss zu Cl2 oxidiert werden.");
t4("Teil 2","Gruppen 17 & 18","Welche Halogenierungsmethode wird für BCl3 und SiCl4 als technisch wichtig genannt?","Carbochlorierung der Elementoxide.","Hydroborierung.","Raschig-Prozess.","Ozonolyse.","C/Cl2 setzt Oxide zu Chloriden um.");
t4("Teil 2","Gruppen 17 & 18","Welche Halogenierungsmethode wird für BF3 und SiF4 bevorzugt genannt?","Protolyse der Elementoxide mit HF.","Carbochlorierung mit Cl2.","Reduktion mit H2.","Elektrolyse von Boraten.","E–F-Verbindungen sind hydrolysestabiler als E–Cl-Analoga.");
t4("Teil 2","Gruppen 17 & 18","Welche generellen Synthesetypen werden für Interhalogenverbindungen aufgelistet?","Metathese, oxidative Addition und Addition/Adduktbildung.","Nur radikalische Polymerisation.","Nur Elektrolyse und Hydroborierung.","Nur Reduktion mit H2.","Drei Syntheseklassen stehen auf der Folie.");
t4("Teil 2","Gruppen 17 & 18","Welches feste Chlorierungsmittel entsteht aus I2 und Cl2 laut Folie?","(ICl3)2.","IF7.","Cl2O7.","I3−.","Die Folie zeigt I2 + 3 Cl2 als Bildungsschritt.");
t4("Teil 2","Gruppen 17 & 18","Welche Aussage unterscheidet F von den schwereren Halogenen bezüglich Oxidationsstufen?","Fluor nimmt in seinen Verbindungen praktisch ausschließlich −I ein.","Fluor bildet besonders stabil +VII.","Fluor besitzt nie −I.","Alle Halogene verhalten sich bezüglich Oxidationsstufe identisch.","F ist das elektronegativste Element.");
t4("Teil 2","Gruppen 17 & 18","Welche Edelgase werden in der Folie als solche genannt, für die molekulare Verbindungen bekannt sind?","Vor allem Kr und Xe.","Nur He und Ne.","Nur Ar.","Ausschließlich Rn.","Schwerere Edelgase sind leichter oxidierbar/polarisierbar.");
t4("Teil 2","Gruppen 17 & 18","Welche Xenon-Spezies gehört laut Übersicht zur Oxidationsstufe +4?","XeOF2.","XeO3.","XeF6.","XeO4.","O = −II und F = −I liefern Xe(+IV) in XeOF2.");
t4("Teil 2","Gruppen 17 & 18","Welche Xenon-Spezies gehört laut Übersicht zur Oxidationsstufe +8?","XeO4.","XeF4.","XeO3.","XeOF4.","Vier O2− ergeben Xe(+VIII).");
t4("Teil 2","Gruppen 17 & 18","Welche Xenon-Fluoridanionen werden für Xe(+6) in der Übersicht aufgeführt?","XeF7− und XeF8^2−.","XeF3+ und XeF5−.","Nur XeF2.","XeF+ und XeF3+.","+6 kann in hochkoordinierten Fluoridanionen auftreten.");
t4("Teil 2","Gruppen 17 & 18","Welches Beispiel für eine Xe–C-Bindung wird genannt?","[Xe–C6F5]+.","Xe(CH3)4.","Xe(CO)6.","XeC2H2.","Perfluorphenyl stabilisiert die ungewöhnliche Bindung.");
t4("Teil 2","Gruppen 17 & 18","Welches Beispiel für eine Xe–N-Bindung wird genannt?","F–Xe–N(SO2F)2.","Xe(NH3)6^2+.","XeN2.","Xe(NO3)4.","Die Übersicht nennt konkrete seltene Bindungstypen.");

// Übergangsmetalle
t4("Teil 2","Übergangsmetalle","Welche übliche Koordinationszahlspanne wird für Ti(IV)-Verbindungen/Komplexe angegeben?","4 bis 6.","Nur 2.","Nur 8 bis 12.","Exakt 1.","Ti(IV) zeigt verschiedene Lewis-saure Koordinationsumgebungen.");
t4("Teil 2","Übergangsmetalle","Welche Eigenschaft besitzen vierfach koordinierte Ti(IV)-Spezies laut Folie besonders?","Sie reagieren als Lewis-Säuren.","Sie sind starke Lewis-Basen.","Sie sind ausschließlich Reduktionsmittel.","Sie sind d10 und inert.","Elektronenarmes Ti(IV).");
t4("Teil 2","Übergangsmetalle","Welche moderne Alternative zum klassischen TiCl4/AlEt3-Ziegler-Natta-System wird genannt?","Metallocen + MAO.","Pd(PPh3)4 + Boronsäure.","Pt/Rh + NH3.","V2O5 + SO2.","MAO = Methylaluminoxan im modernen Metallocen-System.");
t4("Teil 2","Übergangsmetalle","Welche Aussage macht die Folie zu CrF6?","Es wird als einziges bekanntes Cr(VI)-Halogenid genannt, seine Existenz ist jedoch umstritten und es ist extrem instabil.","Es ist das stabilste Chromhalogenid bei Raumtemperatur.","CrF6 existiert als unreaktives Ionengitter.","CrF6 enthält Cr(III).","Hohe Cr-Oxidationsstufen werden durch F am besten stabilisiert.");
t4("Teil 2","Übergangsmetalle","Welche Spezies dient als Nachweis eines Cr(VI)-Peroxokomplexes in etherischer Phase?","[Cr(O)(O2)2].","Cr(CO)6.","CrCl3.","Cr2O3.","Donormoleküle wie Ether stabilisieren den Peroxokomplex.");
t4("Teil 2","Übergangsmetalle","Welche Eigenschaft des Cr(VI)-Peroxids wird ausdrücklich gewarnt?","Es kann sich explosiv zersetzen.","Es ist völlig inert und ungefährlich.","Es ist nur in Wasser stabil und nie reaktiv.","Es ist ein starkes Reduktionsmittel ohne Peroxidbindung.","Peroxo-Cr(VI) ist sehr reaktiv.");
t4("Teil 2","Übergangsmetalle","Welche Manganhalogenid-Oxidationsstufe ist für MnX2 mit X = F, Cl, Br, I stabil?","Mn(II).","Mn(VII).","Mn(VI).","Mn(V).","Die Folie kontrastiert stabile Mn(II)-Halogenide mit instabilen höheren Stufen.");
t4("Teil 2","Übergangsmetalle","Wie werden Mn(VII)-Oxohalogenide/Oxide auf der Folie charakterisiert?","Sehr instabil, starke Oxidationsmittel und bei Raumtemperatur explosiv.","Besonders stabile Reduktionsmittel.","Inerte d10-Komplexe.","Nur als harmlose wässrige Salze bekannt.","Hohe Mn-Oxidationsstufen sind stark oxidierend.");
t4("Teil 2","Übergangsmetalle","Warum sind Metallcarbonyle wie Mn2(CO)10/Re2(CO)10 wichtige Stoffklassen?","Sie sind Grund- und Ausgangsverbindungen der Metallorganischen Chemie.","Sie sind ausschließlich anorganische Pigmente.","Sie werden nur als Elektrolyte verwendet.","Sie besitzen keine M–C-Bindung.","Carbonyle sind synthetisch vielseitige Organometall-Vorstufen.");
t4("Teil 2","Übergangsmetalle","Welches Organometall-Reagenz ist in der Murahashi-Kreuzkupplungsliste angegeben?","Li–R′.","R3Sn–R.","RZnX.","Si–R′.","Murahashi ist in der Folienliste der Pd-Kupplungen aufgeführt.");
t4("Teil 2","Übergangsmetalle","Welches Organometall-Reagenz ist in der Sonogashira-Zeile der Folie angegeben?","Cu–C≡CR′.","B(OH)2R.","Li–R.","R3Sn–R.","Die Tabelle koppelt Sonogashira mit Kupferacetylid.");
t4("Teil 2","Übergangsmetalle","Welche Oxidationsstufen werden für Fe als besonders stabil genannt?","+II und +III.","Nur +I.","Nur +VI.","0 und +VII.","Übersicht der späten 3d-Metalle.");
t4("Teil 2","Übergangsmetalle","Welche Oxidationsstufen werden für Cu als besonders stabil genannt?","+I und +II.","Nur +III.","Nur 0.","+IV und +V.","Kupfer besitzt zwei verbreitete Oxidationsstufen.");
t4("Teil 2","Übergangsmetalle","Welche typische Oxidationsstufe wird für Ag in der Übersicht genannt?","+I.","+III.","+IV.","−I.","Silber(I) ist der klassische Fall.");
t4("Teil 2","Übergangsmetalle","Welche Reaktivität wird auf der Ni(0)-Folie für Ni(CO)4 und Ni(cod)2 hervorgehoben?","Oxidations- und Ligandenaustauschreaktionen.","Nur Protonenabgabe als Brønsted-Säure.","Ausschließlich Bildung ionischer Oxide.","Sie sind grundsätzlich reaktionsunfähig.","Die Folie nennt Oxidationen und Ligandenaustausch als Reaktivität.");
