// AMOC Fragentyp 3 – Neue Folienlücken, Teil D

// Gruppen 1 & 2
t4("Teil 2","Gruppen 1 & 2","Warum gelten Alkalimetalle als starke Reduktionsmittel?","Ihre erste Ionisierungsenergie ist niedrig, sodass sie ihr ns1-Elektron leicht abgeben.","Sie besitzen besonders hohe Elektronenaffinitäten für ein zweites Elektron.","Ihre Valenzschale ist bereits vollständig gefüllt.","Sie bilden keine Kationen.","Elektronenabgabe ist der zentrale Trend.");
t4("Teil 2","Gruppen 1 & 2","Wo findet man laut Folie molekulare Alkalimetall-Spezies wie Na2 besonders?","Vor allem in der Gasphase.","Ausschließlich als stabile Flüssigkeiten bei Raumtemperatur.","Nur in Wasser.","Nur in Ionengittern.","Die kovalente M–M-Bindung ist relativ schwach.");
t4("Teil 2","Gruppen 1 & 2","Wie ist die Na–Na-Bindung in Na2 im Vergleich zur H–H-Bindung charakterisiert?","Deutlich schwächer, obwohl beide im einfachen MO-Bild Bindungsordnung 1 besitzen.","Deutlich stärker als H–H.","Exakt gleich stark wie H–H.","Na2 besitzt keine bindende Wechselwirkung.","Gleiche BO bedeutet nicht gleiche Bindungsenergie.");
t4("Teil 2","Gruppen 1 & 2","Welche Reaktion zeigt die Koordination von THF an Li+?","Li+ + 4 THF ⇌ [Li(THF)4]+.","Li+ + THF → LiH + organische Produkte.","Li+ + 4 THF → Li4THF.","THF reduziert Li+ zu Li(0).","Solvatation als koordinative Bindung.");
t4("Teil 2","Gruppen 1 & 2","Welche Reaktivität zeigt BeH2 gegenüber Lewis-Basen wie THF oder Aminen?","Es bildet Lewis-Säure-Base-Addukte.","Es oxidiert THF quantitativ zu CO2.","Es wird durch Lewis-Basen zu Be(0) reduziert.","Es reagiert mit Donoren grundsätzlich nicht.","Elektronenmangel am Be macht BeH2 Lewis-sauer.");
t4("Teil 2","Gruppen 1 & 2","Welches zweite Reaktivitätsmuster besitzt BeH2 neben seiner Lewis-Acidität?","Hydridische H-Atome reagieren mit Protonenquellen unter H2-Entwicklung.","Es wirkt ausschließlich als Brønsted-Säure.","Es bildet nur Be=H-Doppelbindungen.","Es oxidiert Wasser zu O2.","Lewis-Acidität und Hydridcharakter sind die zwei Folienmotive.");
t4("Teil 2","Gruppen 1 & 2","Welche Anwendung wird für MgH2 diskutiert?","Reversible Wasserstoffspeicherung.","Fluorierung organischer Moleküle.","Katalyse des Ostwald-Verfahrens.","Photoredoxkatalyse.","MgH2 ⇌ Mg + H2.");
t4("Teil 2","Gruppen 1 & 2","Welcher Nachteil von MgH2 als Wasserstoffspeicher wird genannt?","Eine hohe Desorptionstemperatur.","Es kann Wasserstoff nicht reversibel aufnehmen.","Magnesium ist extrem selten.","MgH2 enthält kaum Wasserstoff.","Die Freisetzung von H2 erfordert relativ viel Wärme.");
t4("Teil 2","Gruppen 1 & 2","Was bewirken Ether-Donoren bei festen MgX2-Halogeniden?","Sie koordinieren an Mg2+ und brechen die kristalline Struktur zu solvatisierten Spezies auf.","Sie oxidieren Mg2+ zu Mg3+.","Sie bilden unlösliches elementares Mg.","Sie verhindern jede Koordination.","Beispiele sind MgBr2(OEt2)n.");
t4("Teil 2","Gruppen 1 & 2","Unter welchen Bedingungen werden Grignard-Reagenzien hergestellt?","Wasserfrei in Ether oder THF.","In konzentrierter wässriger Säure.","Unter reinem Sauerstoff.","In flüssigem Ammoniak mit Wasserüberschuss.","Protonenquellen würden RMgX sofort zerstören.");
t4("Teil 2","Gruppen 1 & 2","Welche Reaktion zeigt ein Grignard-Reagenz mit Wasser?","RMgX + H2O → RH + Mg(OH)X.","RMgX + H2O → ROH + MgHX.","RMgX bleibt in Wasser unverändert.","RMgX + H2O → R2Mg + HCl.","Der organische Rest wird protoniert.");
t4("Teil 2","Gruppen 1 & 2","Welches Produkt erhält man nach Umsetzung eines Grignard-Reagenzes mit CO2 und saurer Aufarbeitung?","Eine Carbonsäure RCO2H.","Ein primärer Alkohol.","Ein Alken.","Ein Ether.","CO2 verlängert die C-Kette um ein C-Atom.");
t4("Teil 2","Gruppen 1 & 2","Warum sind Grignard-Reagenzien oft leichter kontrollierbar als Organolithiumreagenzien?","Die C–Mg-Bindung ist weniger stark polarisiert als C–Li; RMgX ist dadurch weniger extrem reaktiv.","RMgX ist grundsätzlich unreaktiv.","Mg ist elektronegativer als C.","RLi ist weniger basisch und weniger polar.","Die Folie kontrastiert Reaktivität und Handhabbarkeit.");

// Gruppe 13
t4("Teil 2","Gruppe 13","Welche Produkte entstehen bei der Hydrolyse von Diboran?","B(OH)3 und H2.","BH3 und O2.","B2O3 und HCl.","Elementares B und H2O2.","Elektronenarmes Diboran reagiert heftig mit Wasser.");
t4("Teil 2","Gruppe 13","Welche Cluster-Vorstufe entsteht laut Folie aus Diboran und NaBH4?","Na[B3H8] unter H2-Abspaltung.","Na[B12H12] direkt ohne Nebenprodukt.","NaBO2.","Na2B4O7 ausschließlich.","Diboran dient als Ausgangsstoff für Borhydrid-Cluster.");
t4("Teil 2","Gruppe 13","Welche Aussage beschreibt die thermische Entwicklung von Diboran zu größeren Boranen?","Unter H2-Abspaltung entstehen elektronenärmere, größere Boran-Cluster.","Diboran zerfällt nur zu elementarem Bor und H2.","Größere Borane entstehen durch Aufnahme von O2.","Der Cluster wird kleiner und wasserreicher.","Elektronenmangel fördert Clusterbildung.");
t4("Teil 2","Gruppe 13","Welche Reaktion zeigt die allgemeine Hydrolyse von BX3?","BX3 + 3 H2O → B(OH)3 + 3 HX.","BX3 + H2O → BH3 + XO2.","BX3 ist gegenüber Wasser inert.","BX3 + 3 H2O → B2H6 + X2.","Sauerstoffdonoren greifen das Lewis-saure Bor an.");
t4("Teil 2","Gruppe 13","Welche Reaktion demonstriert die Lewis-Acidität von BX3 gegenüber Aminen?","BX3 + NR3 → X3B←NR3.","BX3 + NR3 → B3N3 + X2.","BX3 reduziert NR3 zu NH3.","BX3 und NR3 reagieren nicht.","Klassisches Lewis-Säure-Base-Addukt.");
t4("Teil 2","Gruppe 13","Welchen Zugang zu einem Hydridreagenz zeigt die Reaktion von BX3 mit NaH?","Bildung von Na[BH4].","Bildung von LiAlH4.","Bildung von B2H6 ausschließlich.","Bildung von NaOH.","Halogenid wird durch Hydrid ersetzt.");
t4("Teil 2","Gruppe 13","Welche organisch-chemische Rolle von AlCl3 wird explizit hervorgehoben?","Lewis-Säure-Katalysator bei Friedel-Crafts-Reaktionen und elektrophilen aromatischen Substitutionen.","Radikalinitiator der Olefinpolymerisation.","Reduktionsmittel wie LiAlH4.","π-Akzeptorligand an Ni(0).","Molekulares Al2Cl6 ist in organischen Lösungsmitteln wichtig.");
t4("Teil 2","Gruppe 13","Welche Aussage zu InH3 und TlH3 steht auf der Folie?","Sie sind thermisch instabil und nur als Donor-Addukte isolierbar.","Sie sind stabiler als BH3 und AlH3.","Sie bilden bei Raumtemperatur stabile Ionengitter.","Sie existieren ausschließlich als elementare Legierungen.","Hydridstabilität nimmt nach unten stark ab.");
t4("Teil 2","Gruppe 13","Welche Reaktion illustriert den Inert-Pair-Effekt bei Thalliumhalogeniden?","TlBr3 → TlBr + Br2.","TlBr → TlBr3 spontan ohne Oxidationsmittel.","TlH3 → TlBr3 + H2.","TlCl + H2O → TlOH + HCl ausschließlich.","Tl(III) wird zugunsten Tl(I) reduziert.");

// Gruppe 14
t4("Teil 2","Gruppe 14","Warum ist Graphit elektrisch leitfähig, Diamant dagegen isolierend?","Graphit besitzt delokalisierte π-Elektronen im sp2-Schichtsystem; Diamant nur σ-Bindungen im sp3-Netzwerk.","Diamant besitzt mehr freie π-Elektronen als Graphit.","Graphit ist ionisch, Diamant metallisch.","Diamant enthält keine C–C-Bindungen.","Hybridisierung und Delokalisierung unterscheiden sich.");
t4("Teil 2","Gruppe 14","Welche Kohlenstoffmodifikation ist unter Normalbedingungen thermodynamisch stabiler, welche kinetisch besonders stabil?","Graphit ist thermodynamisch stabiler; Diamant ist kinetisch sehr stabil.","Diamant ist thermodynamisch und Graphit kinetisch instabil.","Beide sind thermodynamisch identisch.","Fulleren ist immer die thermodynamisch stabilste Form.","Die Folie stellt genau diesen Gegensatz heraus.");
t4("Teil 2","Gruppe 14","Welche gemeinsame Hybridisierung besitzen Fullerene, Graphen und Kohlenstoffnanoröhren laut Folie?","sp2-Kohlenstoff.","sp3-Kohlenstoff.","sp-Kohlenstoff ausschließlich.","Keine Hybridisierung.","Alle drei basieren auf graphitartigen Netzwerken.");
t4("Teil 2","Gruppe 14","Welche elektronische Eigenschaft von Fullerenen wird hervorgehoben?","Elektronenakzeptor-Eigenschaften.","Sie sind starke Elektronendonoren ohne Akzeptorfunktion.","Sie besitzen keine π-Elektronen.","Sie sind typische ionische Oxide.","Die Folie verknüpft dies u.a. mit K3C60.");
t4("Teil 2","Gruppe 14","Was ist Wasserglas?","Eine wässrige Natriumsilicat-Lösung, Na2SiO3(aq).","Geschmolzenes reines SiO2 ohne Zusätze.","Siliciumtetrachlorid in Wasser.","Ein Polymer aus elementarem Si.","Na2SiO3 wird aus SiO2 und Base zugänglich.");
t4("Teil 2","Gruppe 14","Wie entsteht aus Kieselsäure/Silanolgruppen ein Si–O–Si-Netzwerk?","Durch Kondensation unter Bildung von Siloxanbrücken.","Durch Hydrierung zu SiH4.","Durch Reduktion zu elementarem Si.","Durch Bildung von Si=Si-Doppelbindungen.","Silanolgruppen kondensieren.");
t4("Teil 2","Gruppe 14","Welches Polymer ist das häufigste Silikon laut Folie?","Polydimethylsiloxan (PDMS).","Polyethylen.","Polyphosphazen.","Polystyrol.","Organopolysiloxan mit Si–O–Si-Rückgrat.");
t4("Teil 2","Gruppe 14","Welche Reaktion ist der Kern des Müller-Rochow-Prozesses für Dimethyldichlorsilan?","2 CH3Cl + Si → (CH3)2SiCl2 unter Cu-Katalyse.","SiO2 + 2 C → Si + 2 CO.","SiCl4 + H2 → Si + 4 HCl.","2 SiH4 → Si2H6 + H2.","Direktsynthese von Chlorsilanen.");
t4("Teil 2","Gruppe 14","Wie wird aus (CH3)2SiCl2 schließlich PDMS erzeugt?","Durch Hydrolyse zu Silanolgruppen und anschließende Kondensation.","Durch direkte Reduktion mit LiAlH4 zu PDMS.","Durch Oxidation zu CO2.","Durch Ziegler-Natta-Polymerisation der Si–Cl-Bindung.","Hydrolyse + Polykondensation.");
t4("Teil 2","Gruppe 14","Welche Eigenschaftskombination wird für Silikone genannt?","Flexibel, thermisch und chemisch beständig, hydrophob und elektrisch isolierend.","Spröde, stark hydrophil und elektrisch hochleitend.","Nur bei tiefen Temperaturen stabil.","Stark wasserlöslich und leicht oxidierbar.","Das Si–O–Si-Gerüst bestimmt die Materialeigenschaften.");
t4("Teil 2","Gruppe 14","Warum benötigen isolierbare Silanone Si=O starke kinetische Stabilisierung?","Si=O-Bindungen sind stark polar und reaktive Spezies neigen sonst zu Folgereaktionen/Aggregation.","Si=O ist unpolar und völlig inert.","Silicium kann grundsätzlich kein Sauerstoff binden.","Silanone sind stabile Ionengitter ohne Doppelbindungscharakter.","Die Folie nennt das erste RT-stabile Silanon als Besonderheit.");
t4("Teil 2","Gruppe 14","Welche Struktur besitzen typische Organotetrele von Si und Ge?","Monomere tetraedrische Moleküle.","Ausschließlich ionische Polymere.","Lineare zweikoordinierte Moleküle.","Metallische Cluster.","Sn/Pb werden dagegen aggregationsfreudiger.");
t4("Teil 2","Gruppe 14","Warum oligomerisieren Sn- und Pb-Organohalogenide leichter als Si/Ge-Analoga?","Verbrückende Halogenide werden bei den größeren schweren Zentren begünstigt.","Sn und Pb besitzen keine Valenzorbitale.","Ihre Halogene können nicht koordinieren.","Weil Sn/Pb immer d0 sind.","Größere Zentren begünstigen Brücken und höhere Koordination.");
t4("Teil 2","Gruppe 14","Wie kann die Oligomerisierung von Sn/Pb-Organohalogeniden unterdrückt werden?","Durch sperrige organische Reste.","Durch möglichst kleine Liganden.","Durch Zugabe weiterer Halogenide.","Durch vollständige Entfernung aller organischen Gruppen.","Sterik schützt das Zentrum.");
t4("Teil 2","Gruppe 14","Welche zwei charakteristischen Orbitale besitzen Tetrylene E(II)?","Ein freies Elektronenpaar und ein leeres p-Orbital.","Zwei doppelt besetzte p-Orbitale und kein freies Paar.","Nur ein d-Orbital.","Ein gefülltes π*-Orbital und kein Donororbital.","Divalente Tetrel-Spezies sind ambiphil.");
t4("Teil 2","Gruppe 14","Welcher Aggregationstrend wird für Tetrylene genannt?","Si/Ge/Sn können monomer sein, Pb ist im Festkörper stärker polymerisiert; sperrige Liganden stabilisieren Monomere.","Pb ist am stärksten monomer, Si immer polymer.","Alle Tetrylene sind ausschließlich gasförmig.","Aggregation nimmt zu leichteren Tetrelen zu.","Schwere Tetrele aggregieren stärker.");

// Gruppe 15
t4("Teil 2","Gruppe 15","Welche Zersetzungsreaktion erklärt die extreme Instabilität von NI3?","2 NI3 → N2 + 3 I2.","NI3 + H2O → NH3 + HIO3.","NI3 → N3I + I2.","NI3 ist thermisch völlig stabil.","Stabile N2- und I2-Produkte treiben die Zersetzung.");
t4("Teil 2","Gruppe 15","Warum ist weißer Phosphor P4 so reaktiv?","Die P4-Tetraeder besitzen 60°-Bindungswinkel und starke Ringspannung.","P4 besitzt keine P–P-Bindungen.","Weißer Phosphor ist ein Ionengitter.","Die P–P-Bindungen sind perfekte 180°-Bindungen.","Tetraedrische P4-Ringe sind stark gespannt.");
t4("Teil 2","Gruppe 15","Welche Struktur besitzt roter Phosphor laut Folie?","Verknüpfte P4-Tetraeder bzw. polymerartige (P4)n-Strukturen.","Isolierte P2-Moleküle.","Ein Schichtgitter aus gewellten Sechsringen.","Ein molekulares P8-Käfigsystem.","Schwarzer Phosphor besitzt die Schichtstruktur.");
t4("Teil 2","Gruppe 15","Welche Struktur besitzt schwarzer Phosphor?","Eine Schichtstruktur aus gewellten Sechsringen.","Isolierte P4-Tetraeder.","Eine lineare P∞-Kette.","Ein kubisches Ionengitter.","Er ist halbleiterartig und thermodynamisch stabil.");
t4("Teil 2","Gruppe 15","Wie verändert sich der freie-Elektronenpaar-Charakter von NH3 zu PH3/AsH3/SbH3?","Der s-Charakter nimmt bei den schwereren Pnictogenen zu.","Der p-Charakter nimmt vollständig auf 100 % zu.","Das freie Elektronenpaar verschwindet.","Alle besitzen exakt identische Hybridisierung.","Geringere Hybridisierung führt zu s-reicherem Lone Pair.");
t4("Teil 2","Gruppe 15","Welche Folgerung hat der zunehmende s-Charakter des freien Elektronenpaars bei schweren Pnictogenhydriden?","Die Lewis-Basizität nimmt ab und die Inversionsbarriere steigt.","Die Basizität steigt stark und die Inversionsbarriere sinkt.","Die Moleküle werden planar.","Es hat keinen chemischen Effekt.","Ein tiefer liegendes s-reiches Paar ist schlechter donierbar.");
t4("Teil 2","Gruppe 15","Welche Reaktion oxidiert PCl3 zu POCl3?","2 PCl3 + O2 → 2 POCl3.","PCl3 + H2 → PH3 + Cl2.","PCl3 + O2 → P4O10 + Cl2 ausschließlich.","PCl3 + H2O → POCl3.","Starke P–O-Bindung treibt die Oxidation.");
t4("Teil 2","Gruppe 15","Welche Reaktion nutzt PBr3 zur Umwandlung von Alkoholen?","PBr3 + 3 ROH → 3 RBr + H3PO3.","PBr3 + ROH → R3P + HOBr.","PBr3 oxidiert ROH zu RCHO ohne Bromierung.","PBr3 reagiert mit Alkoholen nicht.","PBr3 ist ein Halogenierungsreagenz.");
t4("Teil 2","Gruppe 15","Welches Mineral bildet den Hauptbestandteil von Knochen und Zähnen laut Folie?","Hydroxylapatit Ca5(PO4)3OH.","Calciumcarbonat CaCO3 ausschließlich.","Na3PO4.","P4O10.","Phosphat ist biologisch strukturell wichtig.");
t4("Teil 2","Gruppe 15","Welche Bindungstypen in ATP werden als energiereiche Phosphorsäureanhydridbindungen bezeichnet?","P–O–P-Bindungen zwischen kondensierten Phosphatgruppen.","P–H-Bindungen.","C–P-Direktbindungen.","P=P-Doppelbindungen.","ATP enthält zwei solcher Anhydridbindungen.");
t4("Teil 2","Gruppe 15","Welche Einheit kann in Polyphosphaten als Verzweigungspunkt wirken?","Eine PO4-Einheit mit entsprechend mehreren kondensierbaren O-Funktionen.","Nur H3PO2.","Nur PH3.","Ein PCl3-Molekül.","Der Kondensationsgrad hängt von verfügbaren OH/O-Funktionen ab.");
t4("Teil 2","Gruppe 15","Welche Eigenschaften werden Polyphosphazenen zugeschrieben?","Hitzebeständig, flammhemmend, elastisch und chemisch beständig.","Nur wasserlöslich und hochentzündlich.","Metallisch leitend und spröde.","Chemisch extrem instabil.","Anwendungen umfassen Membranen und Beschichtungen.");
t4("Teil 2","Gruppe 15","Was geschieht mit Cyclotriphosphazen N3P3Cl6 beim Erhitzen laut Folie?","Der Ring kann sich öffnen und zu Polyphosphazen polymerisieren.","Es zerfällt ausschließlich zu N2 und PCl3.","Es wird zu PF5 fluoriert.","Es bildet elementaren Phosphor.","Ringöffnung führt zum P–N-Rückgrat.");
t4("Teil 2","Gruppe 15","Welche Grenzstruktur ist für Cyclotriphosphazen laut Folie stark bevorzugt?","Eine zwitterionische Grenzstruktur mit stark ionischem P–N-Bindungscharakter.","Eine rein metallische Grenzstruktur.","Nur P=P- und N=N-Doppelbindungen.","Eine vollständig unpolare Struktur.","Die P–N-Bindung ist stark polar.");
